version: "3.8"
services:
  cache_consumer:
    container_name: redis-cache-consumer
    image: redis:alpine
    restart: always
    ports:
      - "6378:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - cache:/data

  mongodb_consumer:
    container_name: "mongo-rtchannels-consumer"
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_DB_PASSWORD}
    env_file: .env
    volumes:
      - ./data/mongo:/data/db

  backend_consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensepi_consumer
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    depends_on:
      - cache_consumer
      - mongodb_consumer

volumes:
  cache:
