# Generated by Django 4.0.4 on 2022-05-04 20:25

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenseHatEnvMeasures',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='SenseHat', max_length=100)),
                ('temperature', models.FloatField(blank=True, default=0.0)),
                ('pressure', models.FloatField(blank=True, default=0.0)),
                ('humidity', models.FloatField(blank=True, default=0.0)),
                ('timestamp', models.DateTimeField(default='2022-05-04 20:25:06')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SenseHatOrientationMeasures',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='SenseHat', max_length=100)),
                ('acceleration_x', models.FloatField(blank=True, default=0.0)),
                ('acceleration_y', models.FloatField(blank=True, default=0.0)),
                ('acceleration_z', models.FloatField(blank=True, default=0.0)),
                ('pitch', models.FloatField(blank=True, default=0.0)),
                ('roll', models.FloatField(blank=True, default=0.0)),
                ('yaw', models.FloatField(blank=True, default=0.0)),
                ('timestamp', models.DateTimeField(default='2022-05-04 20:25:06')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
