# Generated by Django 4.0.4 on 2022-04-21 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveapp', '0003_alter_sensehatenvmeasures_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensehatenvmeasures',
            name='humidity',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='sensehatenvmeasures',
            name='pressure',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='sensehatenvmeasures',
            name='temperature',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='sensehatenvmeasures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 17, 38, 55, 315652)),
        ),
        migrations.AlterField(
            model_name='sensehatorientationmeasures',
            name='acceleration_x',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='sensehatorientationmeasures',
            name='acceleration_y',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='sensehatorientationmeasures',
            name='acceleration_z',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='sensehatorientationmeasures',
            name='pitch',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='sensehatorientationmeasures',
            name='roll',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='sensehatorientationmeasures',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 17, 38, 55, 316653)),
        ),
        migrations.AlterField(
            model_name='sensehatorientationmeasures',
            name='yaw',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
